### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#52] opened 2015-05-19 18:44 UTC
I have a request.
Is it possible that someone could send me the Java Bridge for this bot? I've been trying and trying & researching like crazy, but I just cannot create my own. I just don't have the full knowledge of all the scripting and coding...

Thanks!

**Comment by mathiasbynens** [comment] 2015-05-20 12:39
Duplicate of #3.

**Closed** 2015-05-20 20:21 UTC
